name: Install PHP on Ubuntu 24.04

on: [push, pull_request]
jobs:
  install-php:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        run: |
          sudo apt-get update
          sudo apt-get install -y lsb-release ca-certificates apt-transport-https software-properties-common
          sudo add-apt-repository ppa:ondrej/php -y
          sudo apt-get update
          sudo apt-get install -y php php-cli php-common

      - name: Verify PHP installation
        run: php -v
