name: Install Kotlin and Run Tests

on: [push, pull_request]

jobs:
  install-kotlin:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up helper scripts
        run: |
          mkdir -p $HOME/helpers
          cp -r $GITHUB_WORKSPACE/HELPER_SCRIPTS/* $HOME/helpers/
        shell: bash

      - name: Export HELPER_SCRIPTS environment variable
        run: echo "HELPER_SCRIPTS=$HOME/helpers" >> $GITHUB_ENV

      - name: Run install-kotlin.sh
        run: |
          chmod +x install-kotlin.sh
          ./install-kotlin.sh
        shell: bash

      - name: Verify kotlin installation
        run: |
          kotlin -version
          kotlinc -version
        shell: bash
