name: Install Mercurial via Chocolatey

on: [push, pull_request]

jobs:
  install-mercurial:
    runs-on: windows-latest
    steps:
      - name: Ensure Chocolatey is installed
        run: |
          if (-not (Get-Command choco -ErrorAction SilentlyContinue)) {
            Set-ExecutionPolicy Bypass -Scope Process -Force
            [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
            iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
          }

      - name: Refresh Chocolatey package index (optional)
        run: choco upgrade chocolatey --yes

      - name: Install Mercurial (latest) from Chocolatey
        run: choco install mercurial --yes --no-progress

      - name: Verify Mercurial installation
        run: hg --version
