name: Build Ubuntu Image

on: [push, pull_request]

jobs:
  build-image:
    runs-on: ubuntu-latest
    env:
      UBUNTU_VERSION: "24.04"
      IMAGE_NAME: "custom-ubuntu:${{ github.run_number }}"
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Verify Dockerfile exists
        run: |
          if [ ! -f images/ubuntu/templates/Dockerfile ]; then
            echo "ERROR: Dockerfile not found at images/ubuntu/templates/Dockerfile"
            exit 1
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Ubuntu image with latest version
        run: |
          docker build \
            --build-arg UBUNTU_VERSION=${UBUNTU_VERSION} \
            -t $IMAGE_NAME \
            -f images/ubuntu/templates/Dockerfile \
            images/ubuntu/templates

      - name: Ensure install-php.sh is executable
        run: chmod +x images/ubuntu/scripts/build/install-php.sh

      - name: Run install-php.sh
        run: |
          bash images/ubuntu/scripts/build/install-php.sh
