name: Install PHP Environment

on: [push, pull_request]

jobs:
  install-php:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # If you have helper scripts, ensure they exist; else, skip this step or update paths accordingly.
      - name: (Optional) Prepare helper scripts
        if: ${{ false }} # Set to true and update if you add helper scripts!
        run: |
          mkdir -p $HOME/helpers
          cp scripts/etc-environment.sh $HOME/helpers/etc-environment.sh
          cp scripts/os.sh $HOME/helpers/os.sh
          cp scripts/install.sh $HOME/helpers/install.sh

      # Set HELPER_SCRIPTS env variable (uncomment if using helpers)
      # - name: Set HELPER_SCRIPTS env variable
      #   run: echo "HELPER_SCRIPTS=$HOME/helpers" >> $GITHUB_ENV

      - name: Make install-php.sh executable
        run: chmod +x scripts/install-php.sh

      - name: Run install-php.sh
        run: |
          export HELPER_SCRIPTS=$HOME/helpers
          sudo -E scripts/install-php.sh

      - name: Verify PHP installation
        run: |
          php -v
          composer --version
          phpunit --version
