name: Install R 4.1

on: [push, pull_request]

jobs:
  install-r:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Make install script executable
      run: chmod +x install-rlang.sh

    - name: Install R 4.1
      run: sudo ./install-rlang.sh
