name: Downgrade R Version

on: [push, pull_request]

jobs:
  downgrade-r:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Remove Existing R Version
        run: |
          sudo apt-get remove --purge -y r-base r-base-dev
          sudo apt-get autoremove -y
          sudo apt-get clean

      - name: Add R Repository for Version 4.1
        run: |
          # Add the CRAN repository for Ubuntu 20.04 (focal)
          echo "deb https://cloud.r-project.org/bin/linux/ubuntu focal-cran40

