name: Downgrade R Version

on: [push, pull_request]

jobs:
  downgrade-r:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Remove Existing R Version
        run: |
          sudo apt-get remove --purge -y r-base r-base-dev
          sudo apt-get autoremove -y
          sudo apt-get clean

      - name: Add R Repository for Version 4.1
        run: |
          # Add the CRAN repository for R version 4.1
          echo "deb https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/" | sudo tee -a /etc/apt/sources.list.d/cran-r.list
          
          # Add the GPG key for the R repository
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
  
      - name: Install R Version 4.1
        run: |
          sudo apt-get update
          sudo apt-get install -y r-base=4.1.3-1.2204.0 r-base-dev=4.1.3-1.2204.0

      - name: Verify Installed R Version
        run: |
          R --version
