name: Install and Show UV Version

on: [push, pull_request]

jobs:
  install-and-show-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install pipx
        run: |
          python -m pip install --user pipx
          python -m pipx ensurepath
          export PATH=$PATH:~/.local/bin

      - name: Install uv using pipx and measure time
        run: |
          START_TIME=$(date +%s)
          pipx install uv
          END_TIME=$(date +%s)
          echo "UV installation took $((END_TIME - START_TIME)) seconds."

      - name: Show UV version
        run: uv --version
        
