name: Minimal WSL Python Test

on:
  workflow_dispatch:

jobs:
  wsl-minimal:
    runs-on: windows-2022
    steps:
      - name: Show WSL info
        shell: pwsh
        run: |
          wsl --list --verbose || echo "No WSL distributions installed."

      - name: Try to run Python in WSL
        shell: pwsh
        run: |
          wsl python3 --version || echo "Python not available in WSL."
          wsl python3 -c "print('WSL Python ran successfully')" || echo "Python command failed in WSL."
