name: Minimal WSL Python Test

on: [push, pull_request]

jobs:
  wsl-minimal:
    runs-on: self-hosted
    steps:
      - name: Show WSL info
        run: wsl --list --verbose

      - name: Run Python in WSL
        run: wsl python3 -c "print('WSL Python ran successfully')"
