name: WSL Python Simple Script Test

on: [push, pull_request]

jobs:
  wsl-python-test:
    runs-on: windows-2022
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create simple Python script
        run: echo "print('Hello from WSL Python!')" > test_script.py

      - name: Check for WSL distributions
        id: wsl-check
        shell: pwsh
        run: |
          $wslDistros = wsl -l -q | Where-Object { $_ -ne "" }
          if (-not $wslDistros) {
            Write-Host "No WSL distributions are installed. Cannot proceed with WSL steps."
            exit 1
          } else {
            Write-Host "WSL distributions found: $wslDistros"
          }

      - name: Run simple Python script in WSL
        if: steps.wsl-check.outcome == 'success'
        shell: pwsh
        run: |
          wsl python3 --version || (wsl sudo apt-get update && wsl sudo apt-get install -y python3)
          wsl python3 test_script.py

      - name: Success Message
        if: steps.wsl-check.outcome == 'success'
        run: echo "WSL Python script finished successfully."
